### ISSUE TITLE
Bad Request: can't parse keyboard button: Field "request_user" must be of type Object in TtdReplyKeyboardMarkup

### ISSUE THREAD

**Issue by jlvidal-pav** [dieletro/tinjecttelegram_delphi#6]
When using version 1.4.2 the option "Enviar Texto c/Botones" (TtdReplyKeyboardMarkup), doesn't works .
It seems the new property request_user is not accepted by the API.

**Comment by dieletro** [comment]
send your code so I can understand and help you

**Comment by jlvidal-pav** [comment]
Hi, did not alter your code at the example:

`procedure TForm1.btnEnviarTxtComBtClick(Sender: TObject);
var
bt1, bt2, bt3: TtdKeyboardButton;
begin

  bt1 := TtdKeyboardButton.Create('texto1', FALSE, FALSE);

  bt2 := TtdKeyboardButton.Create('texto2', FALSE, FALSE);

  bt3 := TtdKeyboardButton.Create(VRes_Qual_Meu_ID, FALSE, FALSE);

{
Aqui você cria os botoes do tipo ReplyKeyboard para enviar na mensagem
eles serão criados como um teclado personalizado para seu destinatario
}
  LMarkup := TtdReplyKeyboardMarkup.Create([
  { Primeira Linha }
  [bt1, bt2],
  { Segunda Linha }
  [bt3]], TRUE);


  if BotManager1.IsActive then
  Begin
    if txtID.Text <> '' then
    try
      InjectTelegramBot1.SendMessage(StrToInt64(txtID.Text),
        VRes_MSG_Exemplo_Envio_BT,
        LParseMode, False, False, 0, False, LMarkup)
    except on E: Exception do
      memConsole.Lines.Add(VRes_Falha_Envio_Destinatario + E.Message);
    end;
  End
  else
    Showmessage(VRes_Ative_Servico);
end;`

**Comment by jlvidal-pav** [comment]
After executing, buttons doesn't appear but the error message:

400 - Bad Request: can't parse keyboard button: Field "request_user" must be of type Object

**Comment by dieletro** [comment]
Thanks for reporting, I saw that there really was a bug in this function and thanks to your post, it has already been identified and fixed! Good Codes for you!
