### ISSUE TITLE
Telegram bot management in non-stable networks

### ISSUE THREAD

**Issue by DelphiMan68** [dieletro/tinjecttelegram_delphi#7]
Hello Sir and thanks for your great work,
I have a question that has been bothering me for several hours.

# Question:
The program works properly as long as the connection to the Telegram server is established, but if for any reason the connection is interrupted for even a moment and then it is established, it will no longer be able to respond to the requests that are sent from clients. What is your solution to solve this problem?

**Comment by DelphiMan68** [comment]
I found the solution!
The "OnLog" of "TInjectTelegramExceptionManagerUI" component must exist, otherwise there will be a problem in the program execution process and the program will not be able to respond to incoming requests.
Please update library for fixing this bug. 
Thank you :)

**Comment by dieletro** [comment]
In addition to the Onlog event, you also have the OnDisconect event in the TInjectTelegramBot component which is capable of intercepting the disconnection or loss of internet signal and with this you can place a Time count to wait for reconnection among other forms of Bot stability control that can be used in this event.

**Comment by dieletro** [comment]
In addition to the Onlog event, you also have the OnDisconect event in the TInjectTelegramBot component which is capable of intercepting the disconnection or loss of internet signal and with this you can place a Time count to wait for reconnection among other forms of Bot stability control that can be used in this event.
